export const countryMenuItems = [
  { code: 'us', name: 'Unitied State' },
  { code: 'ca', name: 'Canada' },
  { code: 'it', name: 'Italy' },
  { code: 'fr', name: 'France' },
  { code: 'de', name: 'Germany' },
  { code: 'in', name: 'India' },
  { code: 'jp', name: 'Japan' },
  { code: 'se', name: 'Spain' },
  { code: 'mx', name: 'Mexico' },
  { code: 'uk', name: 'United Kingdom' },
]
export const categoryItems = [
  { code: '1', name: 'Amazon Device Accessories' },
  { code: '2', name: 'Automotive and Powersports' },
  { code: '3', name: 'Baby Products (excluding Baby Apparel)' },
  { code: '4', name: 'Beauty' },
  { code: '5', name: 'Books' },
  { code: '6', name: 'Clothing and Accessories' },
  { code: '7', name: 'Collectible Coins' },
  { code: '8', name: 'Consumer Electronics' },
  { code: '9', name: 'DVD' },
  { code: '10', name: 'Electronics Accessories' },
  { code: '11', name: 'Entertainment Collectibles' },
  { code: '12', name: 'Fine Art' },
  { code: '13', name: 'Furniture (including outdoor furniture) - Mattresses' },
  { code: '14', name: 'Furniture (including outdoor furniture) - Others' },
  { code: '15', name: 'Gift Cards' },
  { code: '16', name: 'Gourmet and Grocery Food' },
  { code: '17', name: 'Health & Personal Care (including Personal Care Appliances)' },
  { code: '18', name: 'Home and Garden (including Pet Supplies)' },
  { code: '19', name: 'Industrial & Scientific (including Food Service and Janitorial & Sanitation)' },
  { code: '20', name: 'Jewelry' },
  { code: '21', name: 'Kitchen' },
  { code: '22', name: 'Major Appliances' },
  { code: '23', name: 'Music' },
  { code: '24', name: 'Musical Instruments' },
  { code: '25', name: 'Office Products' },
  { code: '26', name: 'Outdoors' },
  { code: '27', name: 'Personal Computers' },
  { code: '28', name: 'Shoes' },
  { code: '29', name: 'Software and Computer/Video Games' },
  { code: '30', name: 'Sports (excluding Sports Collectibles)' },
  { code: '31', name: 'Sports Collectibles' },
  { code: '32', name: 'Tools and Home Improvement' },
  { code: '33', name: 'Tools and Home Improvement - Base Equipment Power Tools' },
  { code: '34', name: 'Toys & Games - Collectible Cards' },
  { code: '35', name: 'Toys and Games' },
  { code: '36', name: 'Video Game Consoles' },
  { code: '37', name: 'Watches' },
  { code: '38', name: 'Everything Else' },
]

export enum StateStatus {
  Idel,
  Loading,
  Succeeded,
  Failed,
}

export const InitializedStateSlice = {
  content: {
    tier: 'Content has not been initialized',
    weight: 'Content has not been initialized',
    fba: 'Content has not been initialized',
    referral: 'Content has not been initialized',
    closing: 'Content has not been initialized',
  },
  status: StateStatus.Idel,
  currentCountry: countryMenuItems[0],
}

export enum FbaProductType {
  Normal,
  Apparel,
  Dangerous,
}
