// sync product category by countryCode
export const CountryCategory: Record<string, Array<string>> = {
  us: [
    'Automotive',
    'Electronics',
    'Books',
    'Tools & Home Improvement',
    'Patio, Lawn & Garden',
    'Cell Phones & Accessories',
    'Kitchen & Dining',
    'Camera & Photo',
    'Clothing, Shoes & Jewelry',
    'Sports & Outdoors',
    'Home & Kitchen',
    'Toys & Games',
    'Baby',
    'Office Products',
    'Industrial & Scientific',
    'Music',
    'Musical Instruments',
    'Computers & Accessories',
    'Appliances',
    'Pet Supplies',
    'Arts, Crafts & Sewing',
    'Grocery & Gourmet Food',
    'Video Games',
    'Software',
    'Beauty & Personal Care',
    'Health & Household',
  ],
  uk: [
    'Clothing',
    'Sports & Outdoors',
    'Shoes & Bags',
    'Baby Products',
    'Watches',
    'Home & Kitchen',
    'DIY & Tools',
    'Health & Personal Care',
    'Beauty',
    'Toys & Games',
    'Computers & Accessories',
    'Luggage',
    'Automotive',
    'Electronics & Photo',
    'Large Appliances',
    'Stationery & Office Supplies',
    'Musical Instruments & DJ',
    'Garden & Outdoors',
    'Pet Supplies',
    'Jewellery',
    'Grocery',
    'Lighting',
    'PC & Video Games',
    'Business, Industry & Science',
  ],
  ca: [
    'Automotive',
    'Baby',
    'Beauty & Personal Care',
    'Clothing & Accessories',
    'Electronics',
    'Grocery & Gourmet Food',
    'Health & Personal Care',
    'Industrial & Scientific',
    'Jewelry',
    'Luggage & Bags',
    'Musical Instruments, Stage & Studio',
    'Office Products',
    'Patio, Lawn & Garden',
    'Pet Supplies',
    'Shoes & Handbags',
    'Sports & Outdoors',
    'Tools & Home Improvement',
    'Toys & Games',
    'Watches',
  ],
  de: [
    'Auto & Motorrad',
    'Bücher',
    'Bürobedarf & Schreibwaren',
    'Baby',
    'Baumarkt',
    'Beauty',
    'Bekleidung',
    'Beleuchtung',
    'Computer & Zubehör',
    'DVD & Blu-ray',
    'Drogerie & Körperpflege',
    'Elektro-Großgeräte',
    'Elektronik & Foto',
    'Fremdsprachige Bücher',
    'Games',
    'Garten',
    'Gewerbe, Industrie & Wissenschaft',
    'Haustier',
    'Küche, Haushalt & Wohnen',
    'Kamera & Foto',
    'Koffer, Rucksäcke & Taschen',
    'Lebensmittel & Getränke',
    'Musikinstrumente & DJ-Equipment',
    'Schmuck',
    'Schuhe & Handtaschen',
    'Software',
    'Spielzeug',
    'Sport & Freizeit',
    'Uhren',
  ],
  fr: [
    'Animalerie',
    'Auto & Moto',
    'Bagages',
    'Beauté & Parfum',
    'Bijoux',
    'Bricolage',
    'Bébé & Puériculture',
    'Chaussures & Sacs',
    'Commerce, Industrie & Science',
    'Cuisine & Maison',
    'DVD & Blu-ray',
    'Epicerie',
    'Fournitures de bureau',
    'Gros électroménager',
    'High-tech',
    'Hygiène & Santé',
    'Informatique',
    'Instruments de musique & Sono',
    'Jardin',
    'Jeux & Jouets',
    'Jeux vidéo',
    'Livres',
    'Livres anglais & étrangers',
    'Logiciels',
    'Luminaires & Eclairage',
    'Montres',
    'Sports & Loisirs',
    'Vêtements',
  ],
  in: [
    'Baby',
    'Baby Products',
    'Bags, Wallets & Luggage',
    'Beauty',
    'Books',
    'Car & Motorbike',
    'Clothing & Accessories',
    'Electronics',
    'Gift Cards',
    'Grocery & Gourmet Foods',
    'Health & Personal Care',
    'Home & Kitchen',
    'Industrial & Scientific',
    'Jewellery',
    'Movies & TV Shows',
    'Music',
    'Musical Instruments',
    'Office Products',
    'Pet Supplies',
    'Shoes & Handbags',
    'Software',
    'Sports, Fitness & Outdoors',
    'Toys & Games',
    'Video Games',
    'Watches',
  ],
  it: [
    'Abbigliamento',
    'Alimentari e cura della casa',
    'Auto e Moto',
    'Bellezza',
    'Casa e cucina',
    'CD e Vinili',
    'Elettronica',
    'Fai da te',
    'Film e TV',
    'Giardino e giardinaggio',
    'Giochi e giocattoli',
    'Gioielli',
    'Illuminazione',
    'Commercio, Industria e Scienza',
    'Informatica',
    'Kindle Store',
    'Libri',
    'Libri in altre lingue',
    'Orologi',
    'Prima infanzia',
    'Salute e cura della persona',
    'Scarpe e borse',
    'Software',
    'Sport e tempo libero',
    'Strumenti musicali e DJ',
    'Valigeria',
    'Videogiochi',
    'Buoni regalo',
  ],
  es: [
    'Bebé',
    'Belleza',
    'Bricolaje y herramientas',
    'Coche y moto',
    'Deportes y aire libre',
    'Electrónica',
    'Equipaje',
    'Hogar y cocina',
    'Iluminación',
    'Industria, empresas y ciencia',
    'Informática',
    'Instrumentos musicales',
    'Jardín',
    'Joyería',
    'Juguetes y juegos',
    'Libros',
    'Oficina y papelería',
    'Películas y TV',
    'Relojes',
    'Salud y cuidado personal',
    'Software',
    'Tienda Kindle',
    'Videojuegos',
    'Zapatos y complementos',
    'Ropa',
    'Apps y Juegos',
  ],
  mx: [
    'Bebé',
    'Electrónicos',
    'Tienda Kindle',
    'Ropa, Zapatos y Accesorios',
    'Deportes y Aire Libre',
    'Herramientas y Mejoras del Hogar',
    'Hogar y Cocina',
    'Industria, Empresas y Ciencia',
    'Juguetes y Juegos',
    'Libros',
    'Música',
    'Oficina y papelería',
    'Salud, Belleza y Cuidado Personal',
    'Software',
    'Videojuegos',
    'Instrumentos Musicales',
  ],
  jp: [
    '家電&カメラ',
    '文房具・オフィス用品',
    'ホーム&キッチン',
    'ペット用品',
    'ドラッグストア',
    'ビューティー',
    '食品・飲料・お酒',
    'ベビー&マタニティ',
    '服&ファッション小物',
    'シューズ&バッグ',
    '腕時計',
    'ジュエリー',
    'おもちゃ',
    'ホビー',
    'スポーツ&アウトドア',
    '車&バイク',
    'DIY・工具・ガーデン',
    '大型家電',
    '産業・研究開発用品',
  ],
}

export const getCategoryByCountryCode = (countryCode: string) => {
  return CountryCategory[countryCode] || []
}

export const countryMenuItems = [
  { code: 'us', name: 'Unitied State' },
  { code: 'ca', name: 'Canada' },
  { code: 'it', name: 'Italy' },
  { code: 'fr', name: 'France' },
  { code: 'de', name: 'Germany' },
  { code: 'in', name: 'India' },
  { code: 'jp', name: 'Japan' },
  { code: 'se', name: 'Spain' },
  { code: 'mx', name: 'Mexico' },
  { code: 'uk', name: 'United Kingdom' },
]

export enum StateStatus {
  Idle,
  Loading,
  Succeeded,
  Failed,
}

export const InitializedStateSlice = {
  content: {
    tier: 'Content has not been initialized',
    dimensionalWeight: 'Content has not been initialized',
    packagingWeight: 'Content has not been initialized',
    shippingWeight: 'Content has not been initialized',
    fba: 'Content has not been initialized',
    referral: 'Content has not been initialized',
    closing: 'Content has not been initialized',
  },
  status: StateStatus.Idle,
  currentCountry: countryMenuItems[0],
}

export enum FbaProductType {
  Normal,
  Apparel,
  Dangerous,
}
